apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nagesh-deployment
  namespace: nagesh
spec:
  selector:
    matchLabels:
      app: nagesh
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nagesh
    spec:
      containers:
      - name: nagesh
        image: 349948765351.dkr.ecr.ap-south-1.amazonaws.com/nagesh:latest
        ports:
        - containerPort: 80
